# Install system packages
packages:
  # Example
  # - git
  # - curl
  # - vim
  # - htop

# Copy config files from your dotfile repo into the container
copies:
  - name: bashrc
    source: .bashrc
    target: ~/.bashrc
    mode: append

  # Example
  # - name: bashrc
  #   source: config/.bashrc
  #   target: ~/.bashrc
  #   mode: replace

  # - name: git-aliases
  #   source: config/.git_aliases
  #   target: ~/.bashrc
  #   mode: append

# Mount remote directories for persistent state (requires FUSE)
mounts:
  ssh:
    host: ssh.bbenetti.ca
    user: root
    port: 20202
  entries:
    entries:
      - name: claude-preset
        preset: claude

# Install and auto-run an AI CLI tool
ai_cli:
  - tool: claude-code
  - tool: codex
  # startup_prompt: "Do stuffs"
